### ISSUE TITLE
Should use `Squash and Merge` when you merge a PR

### ISSUE THREAD

**Issue by miniwangdali** [draupnirstudio/Lacerta#11]
You should use `Squash and Merge` when you merge a PR. This will bring you a clear and tidy commit list. And it will benefit from it once you have script to generate change log and auto update the page.
Also, you should format your commit message as:
```
<type>([scope]): <title>

description
```
@Jozdortraz btw, I am not allowed to add a assignee.

**Comment by Jozdortraz** [comment]
Studied!! 
I've granted you the permission of adding an assignee.

btw, can you give me an example of formatted commit message?

**Comment by miniwangdali** [comment]
```
feat(search-skill): Add search skill

1. Add a page for search skill.
2. Add services for search skill.

```

**Comment by Jozdortraz** [comment]
> ```
> feat(search-skill): Add search skill
> 
> 1. Add a page for search skill.
> 2. Add services for search skill.
> ```

Any types other than feat?

**Comment by miniwangdali** [comment]
<type>(<scope>): <message>

<description>

Related to #<issue>

DCO 1.1 Signed-off-by: Developer Name <developer.email@domain.com>

# Types
# - feat: A new feature
# - fix: A bug fix
# - docs: Documentation only changes
# - style: Changes that do not affect the meaning of the code
#    (white-space, formatting, missing semi-colons etc)
# - refactor: A code change that neither fixes a bug, not adds a feature
# - perf: A code change that improves performance
# - test: Adding missing tests
# - chore: Changes to the build process or auxiliary tools and libraries
#    such as documentation generation

**Comment by Jozdortraz** [comment]
> ```
> <type>(<scope>): <message>
> 
> <description>
> 
> Related to #<issue>
> 
> DCO 1.1 Signed-off-by: Developer Name <developer.email@domain.com>
> 
> # Types
> # - feat: A new feature
> # - fix: A bug fix
> # - docs: Documentation only changes
> # - style: Changes that do not affect the meaning of the code
> #    (white-space, formatting, missing semi-colons etc)
> # - refactor: A code change that neither fixes a bug, not adds a feature
> # - perf: A code change that improves performance
> # - test: Adding missing tests
> # - chore: Changes to the build process or auxiliary tools and libraries
> #    such as documentation generation
> ```

666
