### ISSUE TITLE
[Add interview question] How to expand touchable area of a button?

### ISSUE THREAD

**Issue by MikuZZZ** [draupnirstudio/Lacerta#12]
```
.button { 
    position:relative; 
}

.button :after {
    content:'';
    position:absolute;
    top:-10px; 
    bottom:-10px; 
    left:-10px;
    right:-10px; 
}
```

**Comment by Jozdortraz** [comment]
> ```
> .button { 
>     position:relative; 
> }
> 
> .button :after {
>     content:'';
>     position:absolute;
>     top:-10px; 
>     bottom:-10px; 
>     left:-10px;
>     right:-10px; 
> }
> ```

You should wrap the button with a <div> and add a click listener to the div rather than using CSS.

**Comment by Jozdortraz** [comment]
Added.
